org: dsk52
app: sls-api-ts
service: sls-api-ts

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-west-2

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  patterns:
    - '!.build/'

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
